#ifndef MULTIBOOT_H_
#define MULTIBOOT_H_

#define MB_FLAGS_OFFSET 0
#define MB_FRAME_BUFFER_ADDR_OFFSET 22
#define MB_FRAME_BUFFER_WIDTH_OFFSET 25
#define MB_FRAME_BUFFER_HEIGHT_OFFSET 26

#endif // MULTIBOOT_H_
